CREATE TABLE "user"(
  user_id SERIAL PRIMARY KEY NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  UNIQUE (email)
);

CREATE TABLE todo(
  todo_id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  description VARCHAR(255),
  CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES "user" (user_id) ON DELETE CASCADE
);